//
// Generated file, do not edit! Created by opp_msgc 4.3 from src/messages/OBS_Burst.msg.
//

#ifndef _OBS_BURST_M_H_
#define _OBS_BURST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/messages/OBS_Burst.msg</tt> by opp_msgc.
 * <pre>
 * packet OBS_Burst
 * {
 *     @customize(true); 
 *     cQueue messages; 
 *     int numPackets = -1; 
 *     int burstifierId = -1; 
 *     int numSeq = -1; 
 *     int senderId = -1; 
 *     string destNetworkAddr; 
 *     string srcNetworkAddr; 
 *     bool bidirectional = false; 
 *     
 *     
 *     simtime_t StartTimeSlow = -1;
 *     simtime_t StartTimeFast = -1;
 *     int slowChannel = -1; 
 *     int fastChannel = -1; 
 *   
 *     
 *     
 * }
 * </pre>
 *
 * OBS_Burst_Base is only useful if it gets subclassed, and OBS_Burst is derived from it.
 * The minimum code to be written for OBS_Burst is the following:
 *
 * <pre>
 * class OBS_Burst : public OBS_Burst_Base
 * {
 *   private:
 *     void copy(const OBS_Burst& other) { ... }

 *   public:
 *     OBS_Burst(const char *name=NULL, int kind=0) : OBS_Burst_Base(name,kind) {}
 *     OBS_Burst(const OBS_Burst& other) : OBS_Burst_Base(other) {copy(other);}
 *     OBS_Burst& operator=(const OBS_Burst& other) {if (this==&other) return *this; OBS_Burst_Base::operator=(other); copy(other); return *this;}
 *     virtual OBS_Burst *dup() const {return new OBS_Burst(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from OBS_Burst_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(OBS_Burst);
 * </pre>
 */
class OBS_Burst_Base : public ::cPacket
{
  protected:
    cQueue messages_var;
    int numPackets_var;
    int burstifierId_var;
    int numSeq_var;
    int senderId_var;
    opp_string destNetworkAddr_var;
    opp_string srcNetworkAddr_var;
    bool bidirectional_var;
    simtime_t StartTimeSlow_var;
    simtime_t StartTimeFast_var;
    int slowChannel_var;
    int fastChannel_var;

  private:
    void copy(const OBS_Burst_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_Burst_Base&);
    // make constructors protected to avoid instantiation
    OBS_Burst_Base(const char *name=NULL, int kind=0);
    OBS_Burst_Base(const OBS_Burst_Base& other);
    // make assignment operator protected to force the user override it
    OBS_Burst_Base& operator=(const OBS_Burst_Base& other);

  public:
    virtual ~OBS_Burst_Base();
    virtual OBS_Burst_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class OBS_Burst");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual cQueue& getMessages();
    virtual const cQueue& getMessages() const {return const_cast<OBS_Burst_Base*>(this)->getMessages();}
    virtual void setMessages(const cQueue& messages);
    virtual int getNumPackets() const;
    virtual void setNumPackets(int numPackets);
    virtual int getBurstifierId() const;
    virtual void setBurstifierId(int burstifierId);
    virtual int getNumSeq() const;
    virtual void setNumSeq(int numSeq);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual const char * getDestNetworkAddr() const;
    virtual void setDestNetworkAddr(const char * destNetworkAddr);
    virtual const char * getSrcNetworkAddr() const;
    virtual void setSrcNetworkAddr(const char * srcNetworkAddr);
    virtual bool getBidirectional() const;
    virtual void setBidirectional(bool bidirectional);
    virtual simtime_t getStartTimeSlow() const;
    virtual void setStartTimeSlow(simtime_t StartTimeSlow);
    virtual simtime_t getStartTimeFast() const;
    virtual void setStartTimeFast(simtime_t StartTimeFast);
    virtual int getSlowChannel() const;
    virtual void setSlowChannel(int slowChannel);
    virtual int getFastChannel() const;
    virtual void setFastChannel(int fastChannel);
};


#endif // _OBS_BURST_M_H_
