//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

#ifndef __OBSMODULES_MODIFIED_BURSTRECEIVER_H_
#define __OBSMODULES_MODIFIED_BURSTRECEIVER_H_

#include <omnetpp.h>
#include "OBS_Burst.h"
#include <IPv4Datagram.h>
#include <vector>
#include "EdgeDestinationQueue.h"

/**
 * TODO - Generated class
 */

using namespace std;

class BurstReceiver : public cSimpleModule
{
  protected:
    EdgeDestinationQueue *edgequeue; //!< Dispatcher rules.
        EdgeDestinationQueueEntry *tempqueu;

         /* Statistics */
         //cOutVector fakeBursts; //!< Store information here if a burst generated by OBS_FileBurstifier is received.
         //cOutVector VlistSize; //!< Burst list size vector.
       //  int listSize; //!< Burst list size.
         //int recvBursts; //!< Received bursts counter.
         static simsignal_t rcvdPkSignal;
         static simsignal_t rcvdWrongBurstsSignal;


         //list<OBS_Burst*> receivedBursts; //!< Received bursts queue.

         //! Initializer of data structures and statistics.
         virtual void initialize();
         //! Incoming message handler.
         virtual void handleMessage(cMessage *msg);
         //! Record scalars.
      public:
         //! Clean up recvBurst.
         virtual ~BurstReceiver();
    };

#endif
