//
// Generated file, do not edit! Created by opp_msgc 4.3 from src/EdgeNode/OBS_ScheduledBurstItem.msg.
//

#ifndef _OBS_SCHEDULEDBURSTITEM_M_H_
#define _OBS_SCHEDULEDBURSTITEM_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/EdgeNode/OBS_ScheduledBurstItem.msg</tt> by opp_msgc.
 * <pre>
 * packet OBS_ScheduledBurstItem
 * {
 *     int listIndex = -1; 
 *     int burstId = -1; 
 *     simtime_t sendTime = -1; 
 * }
 * </pre>
 */
class OBS_ScheduledBurstItem : public ::cPacket
{
  protected:
    int listIndex_var;
    int burstId_var;
    simtime_t sendTime_var;

  private:
    void copy(const OBS_ScheduledBurstItem& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_ScheduledBurstItem&);

  public:
    OBS_ScheduledBurstItem(const char *name=NULL, int kind=0);
    OBS_ScheduledBurstItem(const OBS_ScheduledBurstItem& other);
    virtual ~OBS_ScheduledBurstItem();
    OBS_ScheduledBurstItem& operator=(const OBS_ScheduledBurstItem& other);
    virtual OBS_ScheduledBurstItem *dup() const {return new OBS_ScheduledBurstItem(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getListIndex() const;
    virtual void setListIndex(int listIndex);
    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);
    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
};

inline void doPacking(cCommBuffer *b, OBS_ScheduledBurstItem& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_ScheduledBurstItem& obj) {obj.parsimUnpack(b);}


#endif // _OBS_SCHEDULEDBURSTITEM_M_H_
