//
// Generated file, do not edit! Created by opp_msgc 4.3 from src/Controller/Connection.msg.
//

#ifndef _CONNECTION_M_H_
#define _CONNECTION_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/Controller/Connection.msg</tt> by opp_msgc.
 * <pre>
 * class Connection
 * {
 *     simtime_t start_time = -1; 
 *         simtime_t end_time = -1;  
 *     int input_port = -1; 
 *        int output_port = -1; 
 *    
 * }
 * </pre>
 */
class Connection : public ::cObject
{
  protected:
    simtime_t start_time_var;
    simtime_t end_time_var;
    int input_port_var;
    int output_port_var;

  private:
    void copy(const Connection& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Connection&);

  public:
    Connection();
    Connection(const Connection& other);
    virtual ~Connection();
    Connection& operator=(const Connection& other);
    virtual Connection *dup() const {return new Connection(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual simtime_t getStart_time() const;
    virtual void setStart_time(simtime_t start_time);
    virtual simtime_t getEnd_time() const;
    virtual void setEnd_time(simtime_t end_time);
    virtual int getInput_port() const;
    virtual void setInput_port(int input_port);
    virtual int getOutput_port() const;
    virtual void setOutput_port(int output_port);
};

inline void doPacking(cCommBuffer *b, Connection& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Connection& obj) {obj.parsimUnpack(b);}


#endif // _CONNECTION_M_H_
