//
// Generated file, do not edit! Created by opp_msgc 4.3 from src/OpticalSwitch/Configure.msg.
//

#ifndef _CONFIGURE_M_H_
#define _CONFIGURE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/OpticalSwitch/Configure.msg</tt> by opp_msgc.
 * <pre>
 * packet Configure {
 *     int inputgate = -1;
 *     int outputgate = -1;
 *     simtime_t starttime = -1; 
 *     simtime_t endtime = -1; 
 *     bool end = false;
 * }
 * </pre>
 */
class Configure : public ::cPacket
{
  protected:
    int inputgate_var;
    int outputgate_var;
    simtime_t starttime_var;
    simtime_t endtime_var;
    bool end_var;

  private:
    void copy(const Configure& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Configure&);

  public:
    Configure(const char *name=NULL, int kind=0);
    Configure(const Configure& other);
    virtual ~Configure();
    Configure& operator=(const Configure& other);
    virtual Configure *dup() const {return new Configure(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getInputgate() const;
    virtual void setInputgate(int inputgate);
    virtual int getOutputgate() const;
    virtual void setOutputgate(int outputgate);
    virtual simtime_t getStarttime() const;
    virtual void setStarttime(simtime_t starttime);
    virtual simtime_t getEndtime() const;
    virtual void setEndtime(simtime_t endtime);
    virtual bool getEnd() const;
    virtual void setEnd(bool end);
};

inline void doPacking(cCommBuffer *b, Configure& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Configure& obj) {obj.parsimUnpack(b);}


#endif // _CONFIGURE_M_H_
